project:
  type: website

website:
  title: "Jared Vasil"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers

format:
  html:
    output-dir: _site      
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true

editor: visual