project:
  type: website
  output-dir: docs

website:
  title: "Jared Vasil"
  navbar:
    left:
      - href: papers.qmd
        text: Publications
        - href: cv.qmd
        text: CV
        text: Code



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true