project:
  type: website
  output-dir: docs

website:
  title: "Jared Vasil"
  navbar:
    left:
    - href: papers.qmd
    text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true