project:
  type: website
  output-dir: docs

website:
  title: "Jared Vasil"
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: papers.qmd
      text: Papers
      
format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true

editor: visual

