project:
  type: website
  output-dir: docs

website:
  title: "Jared Vasil"
  navbar:
    left:
    - text: Publications
      href: papers.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: false